// frontend/src/scenes/default/scenes/member/scenes/users/components/UserForm/index.tsx
import * as React from "react";
import { useFormValue } from "formulizer";
import classnames from "classnames";

import { TextInput } from "../../../../../../../../components/TextInput";
import { Checkbox } from "../../../../../../../../components/Checkbox";
import { Section, Row } from "../../../../../././../../../components/Form";
import { SkeletonLine, SkeletonTextInput } from "../../../../../../../../components/Skeleton";

import styles from "./index.css";

export interface UserFormProps {
    addNew: boolean
}

export interface UserFormValues {
    email: string
	name: string

	studbook_heideschaap: boolean,
	studbook_heideschaap_ko: boolean,

	studbook_schoonebeeker: boolean,
	studbook_schoonebeeker_ko: boolean,

	role_website_contributor: boolean,
	role_studbook_administrator: boolean,
	role_studbook_inspector: boolean
}

export function UserForm(props: UserFormProps) {
    return <>
        <Section title="Inloggegevens">
            <Row label="E-mail" htmlFor="tiem">
                <TextInput type="email" name="email" id="tiem" placeholder="naam@domein.nl" />
            </Row>
            {props.addNew ?
                <Row label="Wachtwoord">
                    <i>Wordt automatisch aangemaakt en verstuurd naar het bovenstaande e-mail adres</i>
                </Row>
            : null
            }
        </Section>
        <Section title="Persoonsgegevens">
            <Row label="Naam" htmlFor="tina">
                <TextInput type="text" id="tina" name="name" />
            </Row>
        </Section>
        <Section title="Stamboeken">
            <Row fullWidth={true}>
                <Checkbox label="Stamboek Drents Heideschaap" name="studbook_heideschaap" />
            </Row>
            <KoSelection name="studbook_heideschaap" />
            <Row fullWidth={true}>
                <Checkbox label="Stamboek Schoonebeeker" name="studbook_schoonebeeker" />
            </Row>
            <KoSelection name="studbook_schoonebeeker" />
        </Section>
        <Section title="Rechten">
            <Row fullWidth={true}>
                <Checkbox label="Website beheerder" name="role_website_contributor" />
            </Row>
            <Row fullWidth={true}>
                <Checkbox label="Stamboek administratie" name="role_studbook_administrator" />
            </Row>
            <Row fullWidth={true}>
                <Checkbox label="Keuringsmeester" name="role_studbook_inspector" />
            </Row>
        </Section>
    </>;
}

export interface UserFormSkeletonProps {
    addNew: boolean
}

export function UserFormSkeleton(props: UserFormSkeletonProps) {
    return <>
        <Section title="Inloggegevens">
            <Row label="E-mail" htmlFor="tiem">
                <SkeletonTextInput />
            </Row>
            {props.addNew ?
                <Row label="Wachtwoord">
                    <SkeletonTextInput />
                </Row>
            : null
            }
        </Section>
        <Section title="Persoonsgegevens">
            <Row label="Naam" htmlFor="tina">
                <SkeletonTextInput />
            </Row>
        </Section>
        <Section title="Stamboeken">
            <Row fullWidth={true}>
                <SkeletonLine />
            </Row>
            <Row fullWidth={true}>
                <SkeletonLine />
            </Row>
            <Row fullWidth={true}>
                <SkeletonLine />
            </Row>
            <Row fullWidth={true}>
                <SkeletonLine />
            </Row>
        </Section>
        <Section title="Rechten">
            <Row fullWidth={true}>
                <SkeletonLine />
            </Row>
            <Row fullWidth={true}>
                <SkeletonLine />
            </Row>
            <Row fullWidth={true}>
                <SkeletonLine />
            </Row>
        </Section>
    </>;
}

interface KoSelectionProps {
	name: string
}

function KoSelection(props: KoSelectionProps) {
	const [isChecked, _] = useFormValue<boolean>(props.name);

	if(!isChecked) {
		return null;
	}

	return <Row fullWidth={true} className={styles.koSelection}>
		<Checkbox label="Kudde overeenkomst" name={props.name + "_ko"} />
	</Row>;
}

// frontend/src/app/member-page/users-page/user-form/user-form.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'app-user-form',
  templateUrl: './user-form.component.html',
  styleUrls: ['./user-form.component.scss']
})
export class UserFormComponent {
  @Input()
  formGroup!: FormGroup

  @Input()
  addNew!: boolean

  constructor() { }
}

export function createFormGroup(): FormGroup {
  return new FormGroup({
    email: new FormControl('', [
      Validators.required,
      Validators.email
    ]),
    name: new FormControl('', [
      Validators.required
    ]),

    studbook_heideschaap: new FormControl(false),
    studbook_heideschaap_ko: new FormControl(false),
    studbook_schoonebeeker: new FormControl(false),
    studbook_schoonebeeker_ko: new FormControl(false),

    role_website_contributor: new FormControl(false),
    role_studbook_administrator: new FormControl(false),
    role_studbook_inspector: new FormControl(false)
  });
}

<div [formGroup]="formGroup">
    <app-form-section title="Inloggegevens">
        <mat-form-field appearance="fill">
            <mat-label>E-mail adres</mat-label>
            <input matInput formControlName="email" />
            <mat-error *ngIf="formGroup.get('email')!.hasError('notUnique')">Opgegeven e-mail is al in gebruik</mat-error>
            <mat-error *ngIf="formGroup.get('email')!.hasError('required')">Verplicht</mat-error>
            <mat-error *ngIf="formGroup.get('email')!.hasError('email')">Vul een geldig e-mail adres in</mat-error>
        </mat-form-field>
        <p *ngIf="addNew">Wachtwoord zal automatisch worden aangemaakt en verstuurd naar het bovenstaande e-mail adres</p>
    </app-form-section>
    <app-form-section title="Persoonsgegevens">
        <mat-form-field appearance="fill">
            <mat-label>Naam</mat-label>
            <input matInput formControlName="name" />
            <mat-error *ngIf="formGroup.get('name')!.hasError('required')">Verplicht</mat-error>
        </mat-form-field>
    </app-form-section>
    <app-form-section title="Stamboek lidmaatschap">
        <mat-checkbox formControlName="studbook_heideschaap" color="primary">Drents Heideschaap</mat-checkbox>
        <div class="ko-field" *ngIf="formGroup.controls.studbook_heideschaap.value">
            <mat-checkbox formControlName="studbook_heideschaap_ko" color="primary">Kuddeovereenkomst</mat-checkbox>
        </div>
        <mat-checkbox class="checkbox" formControlName="studbook_schoonebeeker" color="primary">Schoonebeeker</mat-checkbox>
        <div class="ko-field" *ngIf="formGroup.controls.studbook_schoonebeeker.value">
            <mat-checkbox formControlName="studbook_schoonebeeker_ko" color="primary">Kuddeovereenkomst</mat-checkbox>
        </div>
    </app-form-section>
    <app-form-section title="Rechten">
        <mat-checkbox formControlName="role_website_contributor" color="primary">Website beheerder</mat-checkbox>
        <mat-checkbox class="checkbox" formControlName="role_studbook_administrator" color="primary">Stamboek administratie</mat-checkbox>
        <mat-checkbox class="checkbox" formControlName="role_studbook_inspector" color="primary">Keuringsmeester</mat-checkbox>
    </app-form-section>
</div>
